### ISSUE TITLE
Launch fails on OSX 10.11.2

### ISSUE THREAD

**Issue by cmcconomy** [moforw/albaum#1]
Java version:
`java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)`

When launched with java -jar:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
    no swt-gtk-4527 in java.library.path
    no swt-gtk in java.library.path
    Can't load library: /Users/<name>/.swt/lib/macosx/x86_64/libswt-gtk-4527.jnilib
    Can't load library: /Users/<name>/.swt/lib/macosx/x86_64/libswt-gtk.jnilib`

uname:
 `Darwin <hostname> 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64`

**Comment by moforw** [comment]
Would you mind trying out AlbaumMacos.jar instead?
Thanks,
moforw
